<script src="<?php echo base_url().ADMIN_JS_PATH;?>jquery.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>bootstrap.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>modernizr.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>detect.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>fastclick.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>jquery.slimscroll.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>jquery.blockUI.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>waves.js"></script>
<script src="<?php echo base_url().JS_PATH;?>angular.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>wow.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>jquery.nicescroll.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>jquery.scrollTo.min.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>app.js"></script>
<script src="<?php echo base_url().ADMIN_JS_PATH;?>dropzone.js"></script>
<!-- <script src="<?php echo base_url().ADMIN_JS_PATH;?>sweet-alert.init.js"></script> -->
<script type="text/javascript">$(document).ready(function(){$('form').parsley();});</script>


<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>bootstrap-colorpicker.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>bootstrap-datepicker.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>bootstrap-maxlength.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>bootstrap-timepicker.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>bootstrap-wysihtml5.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>buttons.bootstrap.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>buttons.html5.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>buttons.print.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>chart.min.js"></script>

<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>dataTables.bootstrap.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>dataTables.buttons.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>dataTables.fixedHeader.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>dataTables.keyTable.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>dataTables.responsive.min.js"></script>


<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>excanvas.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>fullcalendar.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>gdp-data.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>gmaps.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.bootstrap-touchspin.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.dataTables.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.crosshair.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.pie.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.resize.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.selection.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.stack.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.time.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.flot.tooltip.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery.knob.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-2.0.2.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-europe-mill-en.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-uk-mill-en.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-us-aea-en.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-us-il-chicago-mill-en.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-jvectormap-world-mill-en.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jquery-ui.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>jszip.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>mindmup-editabletable.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>moment.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>morris.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>numeric-input-example.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>parsley.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>pdfmake.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>raphael-min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>responsive.bootstrap.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>rwd-table.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>summernote.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>sweet-alert.min.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>vfs_fonts.js"></script>
<script src="<?php echo base_url().ADMIN_JSPLUG_PATH;?>wysihtml5-0.3.0.js"></script>
